domain_management/dns/urls.py
from django.urls import path

from dns.views import (
    HostCreateView,
    HostDeleteView,
    HostDetailView,
    HostEditView,
    HostListView,
    RecordCreateView,
    RecordDeleteView,
    RecordEditView,
    RecordListView,
    ZoneCreateView,
    ZoneDeleteView,
    ZoneDetailView,
    ZoneEditView,
    ZoneListView,
)

urlpatterns = [
    path("zones/", ZoneListView.as_view(), name="zone-list"),
    path("zones/create/", ZoneCreateView.as_view(), name="zone-create"),
    path("zones/<slug:pk>/", ZoneDetailView.as_view(), name="zone-detail"),
    path("zones/<slug:pk>/edit", ZoneEditView.as_view(), name="zone-edit"),
    path("zones/<slug:pk>/delete", ZoneDeleteView.as_view(), name="zone-delete"),
    path("hosts/", HostListView.as_view(), name="host-list"),
    path("hosts/create", HostCreateView.as_view(), name="host-create"),
    path("hosts/<slug:pk>/", HostDetailView.as_view(), name="host-detail"),
    path("hosts/<slug:pk>/edit", HostEditView.as_view(), name="host-edit"),
    path("hosts/<slug:pk>/delete", HostDeleteView.as_view(), name="host-delete"),
    path("records/", RecordListView.as_view(), name="record-list"),
    path("records/create", RecordCreateView.as_view(), name="record-create"),
    path("records/<slug:pk>/edit", RecordEditView.as_view(), name="record-edit"),
    path("records/<slug:pk>/delete", RecordDeleteView.as_view(), name="record-delete"),
]

app_name = "dns"

domain_management/domain_management/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from domain_management.forms import LoginForm
from domain_management.views import APIRootView, sso_login_or_redirect

openapi_info = openapi.Info(
    title="Domain Management API",
    default_version="v1",
)

schema_view = get_schema_view(
    openapi_info,
    public=False,
)

urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("", sso_login_or_redirect),
    path("admin/", admin.site.urls),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("__debug__/", include(debug_toolbar.urls)),
    path("dns/", include("dns.urls")),
    path("api/", APIRootView.as_view()),
    path("api/dns/", include("dns.api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/docs/", schema_view.with_ui("swagger"), name="schema-swagger-ui"),
    path("api/redoc/", schema_view.with_ui("redoc"), name="schema-redoc"),
    re_path(
        r"^api/swagger(?P<format>.json|.yaml)$",
        schema_view.without_ui(),
        name="schema-json",
    ),
]

domain_management/templates/base/base.html
{% load static %}
{% load i18n %}

{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
{% get_language_info_list for LANGUAGES as languages %}

{% autoescape on %}
    <!DOCTYPE html>
    <html lang="{{ LANGUAGE_CODE }}">
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Domain management</title>
            <link href="{% static "dist/css/tabler.min.css" %}" rel="stylesheet" />
            <link href="{% static "dist/tabler-icons/tabler-icons.min.css" %}" rel="stylesheet" />

            {% block head %}
            {% endblock head %}

        </head>
        <body>
            <script src="{% static "js/theme-setter.js" %}"></script>

            {% block body %}
            {% endblock body %}

            <script src="{% static "dist/js/tabler.min.js" %}"></script>
        </body>
    </html>
{% endautoescape %}

domain_management/templates/base/error_400.html
{% extends "base/base.html" %}

{% block body %}
    <div class="page page-center">
        <div class="container-tight py-4">
            <div class="empty">
                <div class="empty-header">

                    {% block status_code %}
                    {% endblock status_code %}

                </div>
                <p class="empty-title">

                    {% block error_title %}
                    {% endblock error_title %}

                </p>
                <p class="empty-subtitle text-muted">

                    {% block error_subtitle %}
                    {% endblock error_subtitle %}

                </p>
                <div class="empty-action">

                    {% block action %}
                        <a class="btn btn-primary" onclick="javascript:history.back();">Take me back</a>
                    {% endblock action %}

                </div>
            </div>
        </div>
    </div>
{% endblock body %}

domain_management/templates/base/layout.html
{% extends "base/base.html" %}

{% block body %}
    <div class="antialiased">
        <div class="page">
            {% include "base/navbar.html" %}
            <div class="content">
                <div class="container">
                    <br>

                    {% block content %}
                    {% endblock content %}

                </div>
            </div>
        </div>
    </div>
{% endblock body %}

domain_management/templates/base/navbar.html
<header class="navbar navbar-expand-md navbar-light">
    <div class="container-xl">
        <a class="navbar-brand" href="{% url "dns:zone-list" %}">Domain Management</a>

        <div class="d-s-flex d-md-none dropdown ms-auto me-2 nav-item">
            <a id="id_theme_dropdown_mobile"
               href="#"
               class="nav-link dropdown-toggle"
               data-bs-toggle="dropdown"
               role="button"
               aria-haspopup="true"
               aria-expanded="false">
                <i id="id_theme_icon_mobile" class="ti ti-sun-moon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end"
                 data-bs-popper="none"
                 aria-labelledby="id_theme_dropdown_mobile">
                <a name="auto" class="dropdown-item" onclick="javascript:setTheme('auto');">Auto</a>
                <a name="light" class="dropdown-item" onclick="javascript:setTheme('light');">
                    Light <i class="ti ti-sun ms-2"></i>
                </a>
                <a name="dark" class="dropdown-item" onclick="javascript:setTheme('dark');">
                    Dark <i class="ti ti-moon ms-2"></i>
                </a>
            </div>
        </div>

        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar-menu">
            <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
                <ul class="navbar-nav">
                    <li class="nav-item {% if request.resolver_match.url_name == 'zone-list' %} active" aria-current="true{% endif %}">
                        <a href="{% url "dns:zone-list" %}" class="nav-link">Zones List</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'host-list' %} active" aria-current="true{% endif %}">
                        <a href="{% url "dns:host-list" %}" class="nav-link">Hosts List</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.url_name == 'record-list' %} active" aria-current="true{% endif %}">
                        <a href="{% url "dns:record-list" %}" class="nav-link">Records List</a>
                    </li>
                </ul>
            </div>

            <div class="nav-item navbar-nav order-last">
                <div class="nav-item dropdown">
                    <a id="id_theme_dropdown"
                       href="#"
                       class="nav-link dropdown-toggle"
                       data-bs-toggle="dropdown"
                       role="button"
                       aria-haspopup="true"
                       aria-expanded="false">
                        <i id="id_theme_icon" class="ti ti-sun-moon"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end"
                         data-bs-popper="none"
                         aria-labelledby="id_theme_dropdown">
                        <a name="auto" class="dropdown-item" onclick="javascript:setTheme('auto');">Auto</a>
                        <a name="light" class="dropdown-item" onclick="javascript:setTheme('light');">
                            Light <i class="ti ti-sun ms-2"></i>
                        </a>
                        <a name="dark" class="dropdown-item" onclick="javascript:setTheme('dark');">
                            Dark <i class="ti ti-moon ms-2"></i>
                        </a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a href="#"
                       class="nav-link"
                       data-bs-toggle="dropdown"
                       data-bs-autoclone="outside"
                       role="button"
                       aria-expanded="false">Account</a>
                    <div class="dropdown-menu dropdown-menu-end" data-bs-popper="none">
                        {% if user.is_staff %}
                            <a href="{% url "admin:index" %}" class="dropdown-item">Admin</a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        <form id="logout-form" method="post" action="{% url "logout" %}">
                            {% csrf_token %}
                            <button class="dropdown-item" type="submit">Log out</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>