domain_management/dns/api/urls.py
from django.urls import include, path
from rest_framework import routers

from dns.api.views import (
    DNSUpdateIPv4,
    HostViewSet,
    LegoACMECleanupView,
    LegoACMEPresentView,
    ResourceRecordViewSet,
    ZoneViewSet,
)

router = routers.DefaultRouter()

router.register(r"zones", ZoneViewSet)
router.register(r"hosts", HostViewSet)
router.register(r"records", ResourceRecordViewSet)


urlpatterns = [
    path("acme/lego/present", LegoACMEPresentView.as_view(), name="lego-present"),
    path("acme/lego/cleanup", LegoACMECleanupView.as_view(), name="lego-cleanup"),
    path("ddns/ipv4/fqdns=<fqdns>&ip=<ip>", DNSUpdateIPv4, name="ddns-ipv4"),
    path("", include(router.urls)),
]

app_name = "dns-api"

domain_management/dns/urls.py
from django.urls import path

from dns.views import (
    HostCreateView,
    HostDeleteView,
    HostDetailView,
    HostEditView,
    HostListView,
    RecordCreateView,
    RecordDeleteView,
    RecordEditView,
    RecordListView,
    ZoneCreateView,
    ZoneDeleteView,
    ZoneDetailView,
    ZoneEditView,
    ZoneListView,
)

urlpatterns = [
    path("zones/", ZoneListView.as_view(), name="zone-list"),
    path("zones/create/", ZoneCreateView.as_view(), name="zone-create"),
    path("zones/<slug:pk>/", ZoneDetailView.as_view(), name="zone-detail"),
    path("zones/<slug:pk>/edit", ZoneEditView.as_view(), name="zone-edit"),
    path("zones/<slug:pk>/delete", ZoneDeleteView.as_view(), name="zone-delete"),
    path("hosts/", HostListView.as_view(), name="host-list"),
    path("hosts/create", HostCreateView.as_view(), name="host-create"),
    path("hosts/<slug:pk>/", HostDetailView.as_view(), name="host-detail"),
    path("hosts/<slug:pk>/edit", HostEditView.as_view(), name="host-edit"),
    path("hosts/<slug:pk>/delete", HostDeleteView.as_view(), name="host-delete"),
    path("records/", RecordListView.as_view(), name="record-list"),
    path("records/create", RecordCreateView.as_view(), name="record-create"),
    path("records/<slug:pk>/edit", RecordEditView.as_view(), name="record-edit"),
    path("records/<slug:pk>/delete", RecordDeleteView.as_view(), name="record-delete"),
]

app_name = "dns"

domain_management/domain_management/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from domain_management.forms import LoginForm
from domain_management.views import APIRootView, sso_login_or_redirect

openapi_info = openapi.Info(
    title="Domain Management API",
    default_version="v1",
)

schema_view = get_schema_view(
    openapi_info,
    public=False,
)

urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("", sso_login_or_redirect),
    path("admin/", admin.site.urls),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("__debug__/", include(debug_toolbar.urls)),
    path("dns/", include("dns.urls")),
    path("api/", APIRootView.as_view()),
    path("api/dns/", include("dns.api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api/docs/", schema_view.with_ui("swagger"), name="schema-swagger-ui"),
    path("api/redoc/", schema_view.with_ui("redoc"), name="schema-redoc"),
    re_path(
        r"^api/swagger(?P<format>.json|.yaml)$",
        schema_view.without_ui(),
        name="schema-json",
    ),
]

domain_management/dns/api/views.py
from django.core.exceptions import (
    MultipleObjectsReturned,
    ObjectDoesNotExist,
    PermissionDenied,
)
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import authentication, permissions, viewsets
from rest_framework.decorators import (
    api_view,
    authentication_classes,
    permission_classes,
)
from rest_framework.exceptions import NotFound, ParseError
from rest_framework.response import Response
from rest_framework.views import APIView

from dns.api.serializers import HostSerializer, ResourceRecordSerializer, ZoneSerializer
from dns.models import Host, ResourceRecord, Zone
from dns.utils import get_host_by_acme_fqdn, get_host_by_fqdn


class ZoneViewSet(viewsets.ModelViewSet):
    queryset = Zone.objects.all()
    serializer_class = ZoneSerializer


class HostViewSet(viewsets.ModelViewSet):
    queryset = Host.objects.all()
    serializer_class = HostSerializer


class ResourceRecordViewSet(viewsets.ModelViewSet):
    queryset = ResourceRecord.objects.all()
    serializer_class = ResourceRecordSerializer


class LegoACMEPresentView(APIView):
    authentication_classes = [authentication.BasicAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "fqdn": openapi.Schema(type=openapi.TYPE_STRING, description="FQDN"),
                "value": openapi.Schema(type=openapi.TYPE_STRING, description="Token"),
            },
        )
    )
    def post(self, request, format=None):
        try:
            fqdn = request.data["fqdn"]
            rr_data = request.data["value"]
        except KeyError:
            raise ParseError("Could not determine fqdn and value from request")

        try:
            host = get_host_by_acme_fqdn(fqdn)
            has_acme_perm = request.user.has_perm("dns.verify_acme", host)
        except NotFound:
            has_acme_perm = False

        try:
            acme_host = get_host_by_fqdn(fqdn)
            has_direct_perm = request.user.has_perm("dns.change_host", acme_host)
            has_direct_acme_perm = request.user.has_perm("dns.verify_acme", acme_host)
        except NotFound:
            has_direct_perm = False
            has_direct_acme_perm = False

        if not (has_direct_perm or has_direct_acme_perm or has_acme_perm):
            raise PermissionDenied()

        try:
            acme_host = get_host_by_fqdn(fqdn)
        except NotFound:
            acme_host, _ = Host.objects.get_or_create(
                parent_zone=host.parent_zone, rr_name=f"_acme-challenge.{host.rr_name}"
            )

        try:
            ResourceRecord.objects.get(
                host=acme_host,
                rr_class="IN",
                rr_type="TXT",
                rr_data=rr_data,
                active=True,
            )
        except ObjectDoesNotExist:
            ResourceRecord.objects.create(
                host=acme_host,
                rr_class="IN",
                rr_type="TXT",
                rr_data=rr_data,
                comment="Created via Lego ACME endpoint",
            )
        except MultipleObjectsReturned:
            pass

        resp = {
            "status": "Successful",
            "fqdn": f"{fqdn}",
            "txt": f"{rr_data}",
        }
        return Response(resp, status=200)


class LegoACMECleanupView(APIView):
    authentication_classes = [authentication.BasicAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "fqdn": openapi.Schema(type=openapi.TYPE_STRING, description="FQDN"),
                "value": openapi.Schema(type=openapi.TYPE_STRING, description="Token"),
            },
        )
    )
    def post(self, request, format=None):
        try:
            fqdn = request.data["fqdn"]
            rr_data = request.data["value"]
        except KeyError:
            raise ParseError("Could not determine fqdn and value from request")

        try:
            host = get_host_by_acme_fqdn(fqdn)
            has_acme_perm = request.user.has_perm("dns.verify_acme", host)
        except NotFound:
            has_acme_perm = False

        try:
            acme_host = get_host_by_fqdn(fqdn)
            has_direct_perm = request.user.has_perm("dns.change_host", acme_host)
            has_direct_acme_perm = request.user.has_perm("dns.verify_acme", acme_host)
        except NotFound:
            has_direct_perm = False
            has_direct_acme_perm = False

        try:
            acme_host = get_host_by_fqdn(fqdn)
        except NotFound:
            acme_host = Host.objects.get(
                parent_zone=host.parent_zone, rr_name="_acme-challenge"
            )

        if not (has_direct_perm or has_direct_acme_perm or has_acme_perm):
            raise PermissionDenied()

        try:
            records = ResourceRecord.objects.filter(
                host=acme_host,
                rr_class="IN",
                rr_type="TXT",
                rr_data=rr_data,
                active=True,
            )
            records.delete()
        except ObjectDoesNotExist:
            pass

        resp = {
            "status": "Successful",
            "fqdn": f"{fqdn}",
            "txt": f"{rr_data}",
        }
        return Response(resp, status=200)


@api_view(["GET", "POST"])
@permission_classes((permissions.IsAuthenticated,))
@authentication_classes((authentication.BasicAuthentication,))
@csrf_exempt
def DNSUpdateIPv4(request, fqdns, ip):
    status = 200
    user = request.user
    for fqdn in fqdns.split(","):
        host = get_host_by_fqdn(fqdn)
        created = None
        records = ResourceRecord.objects.filter(
            Q(host=host), Q(rr_class="IN"), Q(rr_type="A"), Q(active=True)
        )
        if len(records) == 1:
            record = records[0]
        elif len(records) == 0:
            if user.has_perm("dns.add_resourcerecord") or user.has_perm(
                "dns.change_host", host
            ):
                record, created = ResourceRecord.objects.get_or_create(
                    host=host, rr_class="IN", rr_type="A", rr_data=ip, active=True
                )
            else:
                raise PermissionDenied()
        else:
            # Keep first record
            record = records[0]
            # Delete others
            records.exclude(pk=record.id).delete()

        if not (
            user.has_perm("dns.change_resourcerecord", record)
            or user.has_perm("dns.change_host", host)
        ):
            raise PermissionDenied()
        # Update ip
        if not created:
            record.rr_data = ip
            record.full_clean()
            record.save()

    resp = {
        "status": "Successful",
        "ip": f"{record.rr_data}",
    }
    return Response(resp, status=status)

domain_management/dns/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin
from guardian.mixins import (
    LoginRequiredMixin,
    PermissionListMixin,
    PermissionRequiredMixin,
)

from dns.filters import (
    HostsFilter,
    ResourceRecordChildFilter,
    ResourceRecordFilter,
    ZoneFilter,
)
from dns.forms import HostForm, ResourceRecordForm, ZoneForm
from dns.models import Host, ResourceRecord, Zone
from dns.tables import (
    ChildHostsTable,
    ChildRecordTable,
    HostsTable,
    ResourceRecordTable,
    ZoneTable,
)


class ZoneDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Zone
    permission_required = "dns.view_zone"
    template_name = "dns/zone_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        child_zones = self.get_object().child_zones.all()
        child_zones_filter = ZoneFilter(
            self.request.GET, queryset=child_zones, prefix="zone"
        )
        context["childzones_filter"] = child_zones_filter
        context["childzones_table"] = ZoneTable(child_zones_filter.qs)

        hosts = self.get_object().hosts.all()
        hosts_filter = HostsFilter(self.request.GET, queryset=hosts, prefix="host")
        context["hosts_filter"] = hosts_filter
        context["hosts_table"] = ChildHostsTable(hosts_filter.qs)

        return context


class ZoneEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Zone
    permission_required = "dns.change_zone"
    template_name = "generic/object_edit.html"
    form_class = ZoneForm


class ZoneListView(
    LoginRequiredMixin, PermissionListMixin, SingleTableMixin, FilterView
):
    model = Zone
    permission_required = "dns.view_zone"
    table_class = ZoneTable
    template_name = "dns/zone_list.html"
    filterset_class = ZoneFilter


class ZoneCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Zone
    permission_required = "dns.add_zone"
    permission_object = None
    accept_global_perms = True
    form_class = ZoneForm
    template_name = "generic/object_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_name"] = self.model.__name__
        return context

    def get_initial(self):
        zone_id = self.request.GET.get("parent_zone", None)
        initial = {"parent_zone": zone_id}
        return initial


class ZoneDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Zone
    permission_required = "dns.delete_zone"
    success_url = reverse_lazy("dns:zone-list")
    template_name = "generic/object_confirm_delete.html"


class HostDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Host
    permission_required = "dns.view_host"
    template_name = "dns/host_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        child_records = self.get_object().all_records.all()
        child_records_filter = ResourceRecordChildFilter(
            self.request.GET, queryset=child_records, prefix="records"
        )
        context["filter"] = child_records_filter
        context["record_table"] = ChildRecordTable(child_records_filter.qs)
        return context


class HostEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Host
    permission_required = "dns.change_host"
    form_class = HostForm
    template_name = "generic/object_edit.html"


class HostListView(
    LoginRequiredMixin, PermissionListMixin, SingleTableMixin, FilterView
):
    model = Host
    permission_required = "dns.view_host"
    table_class = HostsTable
    template_name = "dns/host_list.html"
    filterset_class = HostsFilter


class HostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Host
    permission_required = "dns.add_host"
    permission_object = None
    form_class = HostForm
    template_name = "generic/object_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_name"] = self.model.__name__
        return context

    def get_initial(self):
        zone_id = self.request.GET.get("parent_zone", None)
        initial = {"parent_zone": zone_id}
        return initial


class HostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Host
    permission_required = "dns.delete_host"
    template_name = "generic/object_confirm_delete.html"

    def get_success_url(self) -> str:
        deleted_object = self.get_object()
        parent_id = deleted_object.parent_zone.id
        return reverse_lazy("dns:zone-detail", kwargs={"pk": parent_id})


class RecordEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = ResourceRecord
    permission_required = "dns.change_resourcerecord"
    form_class = ResourceRecordForm
    template_name = "generic/object_edit.html"


class RecordCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = ResourceRecord
    permission_required = "dns.add_resourcerecord"
    permission_object = None
    form_class = ResourceRecordForm
    template_name = "generic/object_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["model_name"] = self.model.__name__
        return context

    def get_initial(self):
        host_id = self.request.GET.get("host", None)
        initial = {"host": host_id}
        return initial


class RecordDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = ResourceRecord
    permission_required = "dns.delete_resourcerecord"
    template_name = "generic/object_confirm_delete.html"

    def get_success_url(self) -> str:
        deleted_object = self.get_object()
        host_id = deleted_object.host.id
        return reverse_lazy("dns:host-detail", kwargs={"pk": host_id})


class RecordListView(
    LoginRequiredMixin, PermissionRequiredMixin, SingleTableMixin, FilterView
):
    model = ResourceRecord
    permission_required = "dns.view_resourcerecord"
    template_name = "dns/record_list.html"
    table_class = ResourceRecordTable
    filterset_class = ResourceRecordFilter

domain_management/templates/dns/host_detail.html
{% extends "generic/object_detail.html" %}

{% load utilities_humanization %}
{% load render_table from django_tables2 %}

{% block page-pretitle %}
    Host Detail
{% endblock page-pretitle %}

{% block object_buttons %}
    <a href="{% url "dns:host-edit" object.id %}" class="btn btn-warning">Edit</a>
    <a href="{% url "dns:host-delete" object.id %}" class="btn btn-danger">Delete</a>
{% endblock object_buttons %}

{% block specific_content %}
    <div class="card">
        <h3 class="card-header">Host information</h3>
        <div class="card-body">
            <div class="datagrid">
                <div class="datagrid-item">
                    <div class="datagrid-title">Active</div>
                    <div class="datagrid-content">{{ object.active | yesno }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Parent Zone</div>
                    <div class="datagrid-content">
                        <a href="{% url "dns:zone-detail" object.parent_zone.id %}">{{ object.parent_zone }}</a>
                    </div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Default TTL</div>
                    <div class="datagrid-content">{{ object.parent_zone.default_ttl | humanize_seconds }}</div>
                </div>
            </div>
        </div>
    </div>

    {% if object.comment %}
        <div class="card mt-4">
            <div class="card-header">
                <h3 class="card-title">
                    <strong>Comment</strong>
                </h3>
            </div>
            <div class="card-body">{{ object.comment }}</div>
        </div>
    {% endif %}

    {% with id_filter_modal="id_filter_modal" %}
        <div class="card mt-4">
            <div class="card-header">
                <h3 class="card-title">
                    <strong>Records</strong>
                </h3>
                <div class="card-actions">
                    {% include "tables/filter_button.html" %}
                    <a href="{% url "dns:record-create" %}?host={{ object.id }}"
                       class="btn btn-success">
                        <i class="ti ti-plus me-2"></i>
                        Create new Record
                    </a>
                </div>
            </div>
            {% include "tables/table_inline.html" with table=record_table %}
        </div>
    {% endwith %}
{% endblock specific_content %}

domain_management/templates/dns/host_list.html
{% extends "generic/object_list.html" %}

{% block createbutton %}
    <a href="{% url "dns:host-create" %}" class="btn btn-success">
        <i class="ti ti-plus me-2"></i>
        Create new Host
    </a>
{% endblock createbutton %}

{% block page-title %}
    Hosts
{% endblock page-title %}

domain_management/templates/dns/record_list.html
{% extends "generic/object_list.html" %}

{% block createbutton %}
    <a href="{% url "dns:record-create" %}" class="btn btn-success">
        <i class="ti ti-plus me-2"></i>
        Create new Record
    </a>
{% endblock createbutton %}

{% block page-title %}
    Records
{% endblock page-title %}

domain_management/templates/dns/zone_detail.html
{% extends "generic/object_detail.html" %}

{% load utilities_humanization %}
{% load render_table from django_tables2 %}

{% block page-pretitle %}
    Zone Detail
{% endblock page-pretitle %}

{% block object_buttons %}
    <a href="{% url "dns:zone-edit" object.id %}" class="btn btn-warning">Edit</a>
    <a href="{% url "dns:zone-delete" object.id %}" class="btn btn-danger">Delete</a>
{% endblock object_buttons %}

{% block specific_content %}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <strong>Zone information</strong>
            </h3>
        </div>
        <div class="card-body">
            <div class="datagrid">
                <div class="datagrid-item">
                    <div class="datagrid-title">Parent zone</div>
                    <div class="datagrid-content">
                        {% if object.parent_zone %}
                            <a href="{% url "dns:zone-detail" object.parent_zone.id %}">{{ object.parent_zone }}</a>
                        {% else %}
                            <span class="text-muted">None</span>
                        {% endif %}
                    </div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Default TTL</div>
                    <div class="datagrid-content">{{ object.default_ttl | humanize_seconds }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">FQDN of primary Nameserver</div>
                    <div class="datagrid-content">{{ object.soa_mname }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Mail contact</div>
                    <div class="datagrid-content">{{ object.soa_rname }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Refresh</div>
                    <div class="datagrid-content">{{ object.soa_refresh | humanize_seconds }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Retry</div>
                    <div class="datagrid-content">{{ object.soa_retry | humanize_seconds }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Expire</div>
                    <div class="datagrid-content">{{ object.soa_expire | humanize_seconds }}</div>
                </div>
                <div class="datagrid-item">
                    <div class="datagrid-title">Negative TTL</div>
                    <div class="datagrid-content">{{ object.soa_negative_ttl | humanize_seconds }}</div>
                </div>
            </div>
        </div>
    </div>

    {% if object.comment %}
        <div class="card mt-4">
            <div class="card-header">
                <h3 class="card-title">
                    <strong>Comment</strong>
                </h3>
            </div>
            <div class="card-body">{{ object.comment }}</div>
        </div>
    {% endif %}

    {% with id_filter_modal="id_filter_zones" filter=childzones_filter %}
        <div class="card mt-4">
            <div class="card-header">
                <h3 class="card-title">
                    <strong>Child Zones</strong>
                </h3>
                <div class="card-actions">
                    {% include "tables/filter_button.html" %}
                    <a href="{% url "dns:zone-create" %}?parent_zone={{ object.id }}"
                       class="btn btn-success">
                        <i class="ti ti-plus me-2"></i>
                        Create new Zone
                    </a>
                </div>
            </div>
            {% include "tables/table_inline.html" with table=childzones_table %}
        </div>
    {% endwith %}

    {% with id_filter_modal="id_filter_hosts" filter=hosts_filter %}
        <div class="card mt-4">
            <div class="card-header">
                <h3 class="card-title">
                    <strong>Hosts</strong>
                </h3>
                <div class="card-actions">
                    {% include "tables/filter_button.html" %}
                    <a href="{% url "dns:host-create" %}?parent_zone={{ object.id }}"
                       class="btn btn-success">
                        <i class="ti ti-plus me-2"></i>
                        Create new Host
                    </a>
                </div>
            </div>
            {% include "tables/table_inline.html" with table=hosts_table %}
        </div>
    {% endwith %}
{% endblock specific_content %}

domain_management/templates/dns/zone_list.html
{% extends "generic/object_list.html" %}

{% block createbutton %}
    <a href="{% url "dns:zone-create" %}" class="btn btn-success">
        <i class="ti ti-plus me-2"></i>
        Create new Zone
    </a>
{% endblock createbutton %}

{% block page-title %}
    Zones
{% endblock page-title %}